# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'API: Regression'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: "D:/a/1/s/RegressionApiTests/bin/Release/netcoreapp3.1/RegressionApiTests.dll"
    uiTests: false
    runSettingsFile: "D:/a/1/s/TestConfigurator/RunSettings/InstanceSettings.runsettings"
    testRunTitle: 'API: Regression'
    runTestsInIsolation: true
    rerunFailedTests: true
    rerunMaxAttempts: 2
  continueOnError: true
    
    
- task: VSTest@2
  displayName: 'UI: Regression E2E Tests'
  inputs:
    testAssemblyVer2: 'D:/a/1/s/RegressionUiTests/bin/Debug/netcoreapp3.1/RegressionUiTests.dll'
    uiTests: true
    runSettingsFile: 'D:/a/1/s/TestConfigurator/RunSettings/InstanceSettings.runsettings'
    runTestsInIsolation: true
    testRunTitle: 'UI: Regression'
    rerunFailedTests: true
    rerunMaxAttempts: 1
    runInParallel: true
  continueOnError: true
