# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

parameters:
  - name: 'TestApiRegression'
    displayName: 'API: Regression Tests'
    type: boolean
    default: false
  - name: 'TestUIRegression'
    displayName: 'UI Regression Tests'
    type: boolean
    default: false

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   displayName: 'UI: Regression API Tests2'
#   condition: eq(${{ parameters.TestApiRegression }}, 'true')
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
#     testAssemblyVer2: "$(Build.Repository.LocalPath)/RegressionApiTests/bin/Release/netcoreapp3.1/RegressionApiTests.dll"
#     uiTests: false
#     runSettingsFile: "$(Build.Repository.LocalPath)/TestConfigurator/RunSettings/InstanceSettings.runsettings"
#     testRunTitle: 'API: Regression'
#     runTestsInIsolation: true
#     rerunFailedTests: true
#     rerunMaxAttempts: 2
#   continueOnError: true

# - task: VSTest@2
#   displayName: 'UI: Regression E2E Tests2'
#   condition: eq(${{ parameters.TestUIRegression }}, 'true')
#   inputs:
#     testAssemblyVer2: '$(Build.Repository.LocalPath)/RegressionUiTests/bin/Release/netcoreapp3.1/RegressionUiTests.dll'
#     uiTests: true
#     runSettingsFile: '$(Build.Repository.LocalPath)/TestConfigurator/RunSettings/InstanceSettings.runsettings'
#     runTestsInIsolation: true
#     testRunTitle: 'UI: Regr'
#     rerunFailedTests: true
#     rerunMaxAttempts: 1
#     runInParallel: true
#   continueOnError: true

#
#
#
# - task: DotNetCoreCLI@2
#   displayName: 'Run API Tests'
#   inputs:
#     command: 'test'
#     publishTestResults: 
#     projects: '$(Build.Repository.LocalPath)/RegressionApiTests/bin/Release/netcoreapp3.1/RegressionApiTests.dll'
#     arguments: '--logger trx --logger junit --results-directory $(Build.Repository.LocalPath)\API --settings $(Build.Repository.LocalPath)/TestConfigurator/RunSettings/InstanceSettings.runsettings'
#     testRunTitle: 'API: Regression API Tests'

# - task: DotNetCoreCLI@2
#   displayName: 'Run UI Tests'
#   inputs:
#     command: 'test'
#     projects: '$(Build.Repository.LocalPath)/RegressionUiTests/bin/Release/netcoreapp3.1/RegressionUiTests.dll'
#     arguments: '--logger trx --logger junit --results-directory $(Build.Repository.LocalPath)\UI --settings $(Build.Repository.LocalPath)/TestConfigurator/RunSettings/InstanceSettings.runsettings'
#     testRunTitle: 'UI: Regression API Tests'

#
#
#
- task: DotNetCoreCLI@2
  displayName: 'Run API Tests'
  inputs:
    command: 'test'
    projects: '$(Build.Repository.LocalPath)/RegressionApiTests/bin/Release/netcoreapp3.1/RegressionApiTests.dll'
    arguments: '--logger trx --logger junit --settings $(Build.Repository.LocalPath)/TestConfigurator/RunSettings/InstanceSettings.runsettings'
    testRunTitle: 'API: Regression API Tests'
  continueOnError: true
- task: CmdLine@2
  displayName: 'Renaming API XML Test Results'
  inputs:
    script: 'move D:\a\_temp\TestResults.xml D:\a\_temp\TestResults_API.xml'

- task: DotNetCoreCLI@2
  displayName: 'Run UI Tests'
  inputs:
    command: 'test'
    projects: '$(Build.Repository.LocalPath)/RegressionUiTests/bin/Release/netcoreapp3.1/RegressionUiTests.dll'
    arguments: '--logger trx --logger junit'
    testRunTitle: 'UI: Regression UI Tests'
  continueOnError: true

- task: CmdLine@2
  displayName: 'Renaming UI XML Test Results'
  inputs:
    script: 'move D:\a\_temp\TestResults.xml D:\a\_temp\TestResults_UI.xml'

- task: CmdLine@2
  displayName: 'Print out results'
  inputs:
    script: 'dir'
- task: CmdLine@2
  displayName: 'Create ZIP'
  inputs:
    script: 'cd D:\a\_temp\ tar.exe -a -c -f out.zip *.xml'
    
- task: CmdLine@2
  displayName: 'Print out results'
  inputs:
    script: 'dir D:\a\_temp\'    

#- task: CmdLine@2
#  displayName: 'Jira'
#  inputs:
#    script: 'curl -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4ZTc0MTNiNy0yMDVjLTM2ZDctYmIzNy01YWUxODZhNTE0MTkiLCJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczpcL1wvYXdvaGEuYXRsYXNzaWFuLm5ldCIsInVzZXIiOnsiYWNjb3VudElkIjoiNTU3MDU4OmE5YTk0NTlkLTRhMTgtNDc3Ni04ZTkyLThmOGY0MjgyMTA2ZCJ9fSwiaXNzIjoiY29tLmthbm9haC50ZXN0LW1hbmFnZXIiLCJleHAiOjE2OTY4NzUyNTAsImlhdCI6MTY2NTMzOTI1MH0.hfT3D0jvO2OKWj48GK6dqFk0II2wGtJFNagnBYVLtTI" -F "file=@D:\a\_temp\TestResults.xml" https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey="TES"'